//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 03:04:40 PM GFT 
//


package ar.edu.unicen.exa.games.gameschema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ar.edu.unicen.exa.games.gameschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GameProperties_QNAME = new QName("http://www.games.exa.unicen.edu.ar/GameSchema", "gameProperties");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ar.edu.unicen.exa.games.gameschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlProperty }
     * 
     */
    public XmlProperty createXmlProperty() {
        return new XmlProperty();
    }

    /**
     * Create an instance of {@link XmlDiscretizer }
     * 
     */
    public XmlDiscretizer createXmlDiscretizer() {
        return new XmlDiscretizer();
    }

    /**
     * Create an instance of {@link XmlParam }
     * 
     */
    public XmlParam createXmlParam() {
        return new XmlParam();
    }

    /**
     * Create an instance of {@link XmlFilter }
     * 
     */
    public XmlFilter createXmlFilter() {
        return new XmlFilter();
    }

    /**
     * Create an instance of {@link XmlInterval }
     * 
     */
    public XmlInterval createXmlInterval() {
        return new XmlInterval();
    }

    /**
     * Create an instance of {@link XmlGameProperties }
     * 
     */
    public XmlGameProperties createXmlGameProperties() {
        return new XmlGameProperties();
    }

    /**
     * Create an instance of {@link XmlDiscretization }
     * 
     */
    public XmlDiscretization createXmlDiscretization() {
        return new XmlDiscretization();
    }

    /**
     * Create an instance of {@link XmlFiltering }
     * 
     */
    public XmlFiltering createXmlFiltering() {
        return new XmlFiltering();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlGameProperties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.games.exa.unicen.edu.ar/GameSchema", name = "gameProperties")
    public JAXBElement<XmlGameProperties> createGameProperties(XmlGameProperties value) {
        return new JAXBElement<XmlGameProperties>(_GameProperties_QNAME, XmlGameProperties.class, null, value);
    }

}
