//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 03:04:40 PM GFT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.games.exa.unicen.edu.ar/GameSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ar.edu.unicen.exa.games.gameschema;
